#-------fsmyara--------------------------------------------
syf: fsmyaraa.vbe \
     fsmyaraj.vbe \
     fsmyaram.vbe \
     fsmyarao.vbe \
     fsmyarar.vb
boom : fsmyaraa_b.vbe\
		fsmyaraj_b.vbe\
		fsmyarar_b.vbe\
		fsmyaram_b.vbe\
		fsmyarao_b.vbe
boog : fsmyaraa_b.vst\
		fsmyaraj_b.vst\
		fsmyaram_b.vst\
		fsmyarao_b.vst\
		fsmyarar_b.vst

loon : fsmyaraa_b_l.vst\
		fsmyaraj_b_l.vst\
		fsmyaram_b_l.vst\
		fsmyarao_b_l.vst\
		fsmyarar_b_l.vst

flatbeh: fsmyaraa_b_l_net.vbe
		@echo "<-- Generated FLATBEH and PROOF"		

dft: fsmyaraa_dft.vst
		@echo "<-- Generated DFT"


#-------Finite State Machine Synthesis-----------------#
vhd_to_fsm:
	rename .vhd .fsm *.vhd

fsmyaraa.vbe: fsmyara.fsm
	@echo "    Encoding Synthesis -> fsmyaraa.vbe"
	syf -CEV -a fsmyara
 
fsmyaraj.vbe: fsmyara.fsm
	@echo "    Encoding Synthesis  -> fsmyaraj.vbe"
	syf -CEV -j fsmyara
 
fsmyaram.vbe: fsmyara.fsm
	@echo "    Encoding Synthesis  ->fsmyaram.vbe"
	syf -CEV -m fsmyara
 
fsmyarao.vbe: fsmyara.fsm
	@echo "    Encoding Synthesis  -> fsmyarao.vbe"
	syf -CEV -o fsmyara
 
fsmyarar.vbe: fsmyara.fsm
	@echo "    Encoding Synthesis  -> fsmyarar.vbe"
	syf -CEV -r fsmyara

%_b.vbe: %.vbe
	@echo "    Boolean Optimization  -> $@"
	boom -V -d 50 $* $*_b>$*_boom.out 
	
%.vst: %.vbe paramfile.lax
	@echo "    Logical Synthesis  -> $@"
	boog -x 1 -l paramfile $* > $*_boog.out 
	
%_l.vst: %.vbe paramfile.lax
	@echo "    Netlist Optimization  -> $@"
	loon -x 1 -l paramfile $* $*_l > $*_loon.out 
	
%_b_l_net.vbe: %_b_l.vst %.vbe
	@echo "    Formal checking  -> $@"
	flatbeh $*_b_l $*_b_l_net > $*_flatbeh.out 
	proof -d $* $*_b_l_net > $*_proof.out
	
fsmyaraa_dft.vst : fsmyaraa_b_l.vst  fsmyaraa_dft.vst
	@echo "    DFT  -> $@"
	scapin -VRB fsmyaraa_b_l path fsmyaraa_dft> fsmyaraa_DFT.out


#-------Clean Up---------------------------------------#

clean :
	rm -f  *.vbe *.enc *~
	@echo "Erase all the files generated by the makefile"

